<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>EZRecoil</RootNamespace>
    <AssemblyName>EZRecoil</AssemblyName>
    <Version>1.0.0</Version>
    <ApplicationIcon>EZ_Recoil.ico</ApplicationIcon>
  </PropertyGroup>

  <!-- 独立发布设置：指定 -r win-x64 时自动启用 自包含 + 单文件 -->
  <PropertyGroup Condition="'$(RuntimeIdentifier)' != ''">
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <None Include="JsonRAW\**" CopyToOutputDirectory="PreserveNewest" />
    <Resource Include="EZ_Recoil.ico" />
  </ItemGroup>

</Project>
